[package]
name = "Rustify"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.21.1"
eframe = "0.29.1"
rand = "0.8.5"
symphonia = "0.5.4"
image = "0.25.5"
crossbeam-channel = "0.5.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
