[package]
name = "Rustify"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.20.1"
eframe = "0.29.1"
rand = "0.8.5"
symphonia = "0.5.4"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.139"
image = "0.25.5"
